CREATE TABLE PRODUCTO(
ID NUMBER GENERATED BY DEFAULT AS IDENTITY, 
descripcion varchar(100),
largo number(10,2),
ancho number(10,2),
color varchar(12),
codigoBarra varchar(15) UNIQUE,
primary key(id)
);


create or replace PROCEDURE SP_PRODUCTO_INSERT(descripcion varchar, largo number,ancho number,color varchar,codigoBarra varchar,pcursor out sys_refcursor, pcodigo out number, mensaje out varchar)
as
BEGIN     
    BEGIN
       INSERT INTO PRODUCTO (descripcion, largo,ancho,color,codigoBarra)
       VALUES (descripcion, largo,ancho,color,codigoBarra)
       RETURNING ID INTO pcodigo;
       commit;

       mensaje := '000 - Registro Exitoso';
    EXCEPTION    
        WHEN OTHERS THEN
          RAISE_APPLICATION_ERROR(-20001,'ERROR AL REGISTRAR EL PRODUCTO '||descripcion);
          mensaje:='002 - Ha ocurrido un error al registrar el producto';                
          RETURN;          
    END;

    open pcursor for 
    Select id,descripcion, largo,ancho,color,codigoBarra from producto order by id;
END;